#!/usr/bin/env python3
"""
CVG Test Generator - GitHub Action Core
Generate unit tests, integration tests, and E2E tests automatically
"""
import argparse
import json
import os
import sys
import subprocess
from pathlib import Path
from datetime import datetime

def analyze_code(path: str, language: str):
    """Analyze source code to identify testable functions/classes"""
    testable_items = []
    path = Path(path)
    
    if language == "auto":
        py_files = list(path.rglob("*.py"))
        rs_files = list(path.rglob("*.rs"))
        ts_files = list(path.rglob("*.ts"))
        go_files = list(path.rglob("*.go"))
        java_files = list(path.rglob("*.java"))
        
        if py_files:
            language = "python"
            files = py_files
        elif rs_files:
            language = "rust"
            files = rs_files
        elif ts_files:
            language = "typescript"
            files = ts_files
        elif go_files:
            language = "go"
            files = go_files
        elif java_files:
            language = "java"
            files = java_files
        else:
            return testable_items, "unknown"
    else:
        extensions = {"python": "*.py", "rust": "*.rs", "typescript": "*.ts", "go": "*.go", "java": "*.java"}
        files = list(path.rglob(extensions.get(language, "*.py")))
    
    for file in files[:50]:  # Limit to 50 files
        try:
            content = file.read_text()
            if language == "python":
                for line in content.split('\n'):
                    stripped = line.strip()
                    if stripped.startswith('def ') and not stripped.startswith('def _'):
                        func_name = stripped.split('def ')[1].split('(')[0]
                        testable_items.append({"file": str(file), "type": "function", "name": func_name})
                    elif stripped.startswith('class ') and not stripped.startswith('class _'):
                        class_name = stripped.split('class ')[1].split('(')[0].split(':')[0]
                        testable_items.append({"file": str(file), "type": "class", "name": class_name})
            elif language == "rust":
                for line in content.split('\n'):
                    if 'fn ' in line and not 'fn _' in line:
                        func_name = line.split('fn ')[1].split('(')[0].strip()
                        testable_items.append({"file": str(file), "type": "function", "name": func_name})
            elif language == "typescript":
                for line in content.split('\n'):
                    stripped = line.strip()
                    if 'function ' in stripped or '=>' in stripped:
                        if 'function ' in stripped:
                            func_name = stripped.split('function ')[1].split('(')[0].strip()
                        else:
                            func_name = stripped.split('=')[0].strip().replace('const ', '').replace('let ', '').replace('var ', '')
                        if func_name and not func_name.startswith('_'):
                            testable_items.append({"file": str(file), "type": "function", "name": func_name})
            elif language == "go":
                for line in content.split('\n'):
                    if 'func ' in line and not 'func _' in line:
                        func_name = line.split('func ')[1].split('(')[0].strip()
                        if func_name[0].isupper():  # Exported functions
                            testable_items.append({"file": str(file), "type": "function", "name": func_name})
            elif language == "java":
                for line in content.split('\n'):
                    stripped = line.strip()
                    if ('public' in stripped or 'private' in stripped) and ('void' in stripped or 'int' in stripped or 'String' in stripped):
                        parts = stripped.split()
                        for i, p in enumerate(parts):
                            if '(' in p:
                                func_name = p.split('(')[0]
                                if func_name and not func_name.startswith('_'):
                                    testable_items.append({"file": str(file), "type": "method", "name": func_name})
                                break
        except Exception as e:
            print(f"Error analyzing {file}: {e}")
    
    return testable_items, language

def generate_tests(items, language, test_type):
    """Generate test code based on analysis"""
    tests = []
    
    if language == "python":
        for item in items:
            if item["type"] == "function":
                test_code = f'''
def test_{item["name"]}():
    """Test for {item['name']} - auto-generated by CVG Test Generator"""
    # TODO: Add assertions for {item['name']}
    # File: {item['file']}
    pass
'''
            elif item["type"] == "class":
                test_code = f'''
class Test{item["name"]}:
    """Tests for {item['name']} - auto-generated by CVG Test Generator"""
    # TODO: Add test methods for {item['name']}
    # File: {item['file']}
    def test_instantiation(self):
        pass
'''
            tests.append({"file": item["file"], "test": test_code, "type": item["type"], "name": item["name"]})
    
    elif language == "rust":
        for item in items:
            test_code = f'''
#[test]
fn test_{item["name"]}() {{
    // Test for {item['name']} - auto-generated by CVG Test Generator
    // TODO: Add assertions for {item['name']}
    // File: {item['file']}
}}
'''
            tests.append({"file": item["file"], "test": test_code, "type": item["type"], "name": item["name"]})
    
    elif language == "typescript":
        for item in items:
            test_code = f'''
test("{item["name"]}", () => {{
  // Test for {item['name']} - auto-generated by CVG Test Generator
  // TODO: Add assertions for {item['name']}
  // File: {item['file']}
  expect(true).toBe(true);
}});
'''
            tests.append({"file": item["file"], "test": test_code, "type": item["type"], "name": item["name"]})
    
    elif language == "go":
        for item in items:
            test_code = f'''
func Test{item["name"]}(t *testing.T) {{
    // Test for {item['name']} - auto-generated by CVG Test Generator
    // TODO: Add assertions for {item['name']}
    // File: {item['file']}
}}
'''
            tests.append({"file": item["file"], "test": test_code, "type": item["type"], "name": item["name"]})
    
    elif language == "java":
        for item in items:
            test_code = f'''
@Test
void test{item["name"]}() {{
    // Test for {item['name']} - auto-generated by CVG Test Generator
    // TODO: Add assertions for {item['name']}
    // File: {item['file']}
}}
'''
            tests.append({"file": item["file"], "test": test_code, "type": item["type"], "name": item["name"]})
    
    return tests

def create_pr(token, repo, branch, title, body):
    """Create PR via GitHub API"""
    import urllib.request
    url = f"https://api.github.com/repos/{repo}/pulls"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = json.dumps({
        "title": title,
        "head": branch,
        "base": "main",
        "body": body
    }).encode()
    
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode())
            return result.get("html_url")
    except Exception as e:
        print(f"PR creation failed: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description='CVG Test Generator')
    parser.add_argument('-target-path', nargs='?', default='.')
    parser.add_argument('-language', nargs='?', default='auto')
    parser.add_argument('-test-type', nargs='?', default='unit')
    parser.add_argument('-coverage', nargs='?', default='80')
    parser.add_argument('-create-pr', nargs='?', default='true')
    parser.add_argument('-pr-title', nargs='?', default='[CVG] Add generated tests')
    
    args, _ = parser.parse_known_args()
    
    print(f"[{datetime.now().isoformat()}] Analyzing {args.target_path}...")
    
    items, lang = analyze_code(args.target_path, args.language)
    print(f"Found {len(items)} testable items in {lang}")
    
    if not items:
        print("No testable items found. Exiting.")
        return
    
    tests = generate_tests(items, lang, args.test_type)
    
    output = {
        "analysis": {
            "path": args.target_path,
            "language": lang,
            "test_type": args.test_type,
            "coverage_target": args.coverage,
            "items_found": len(items)
        },
        "tests": tests,
        "generated_at": datetime.now().isoformat()
    }
    
    print(json.dumps(output, indent=2))
    
    # Save results
    output_path = Path(args.target_path) / ".cvg-tests" / f"{args.test_type}_output.json"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(json.dumps(output, indent=2))
    print(f"\nResults saved to {output_path}")
    
    # Create test files in the repo
    if lang == "python":
        test_dir = Path(args.target_path) / "tests"
        test_dir.mkdir(exist_ok=True)
        
        for test in tests:
            test_file = test_dir / f"test_{test['name']}.py"
            test_file.write_text(test["test"])
            print(f"Created test file: {test_file}")
    
    # Create PR if requested
    if args.create_pr.lower() == 'true':
        github_token = os.environ.get('GITHUB_TOKEN') or os.environ.get('INPUT_GITHUB_TOKEN')
        repo = os.environ.get('GITHUB_REPOSITORY')
        branch = os.environ.get('GITHUB_HEAD_REF') or f"cvg-tests-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        
        if github_token and repo:
            pr_url = create_pr(github_token, repo, branch, args.pr_title, 
                f"Auto-generated tests by CVG Test Generator\n\n- Language: {lang}\n- Test type: {args.test_type}\n- Items found: {len(items)}\n- Coverage target: {args.coverage}%\n\nGenerated: {datetime.now().isoformat()}")
            if pr_url:
                print(f"PR created: {pr_url}")
        else:
            print("PR creation skipped (missing GITHUB_TOKEN or GITHUB_REPOSITORY)")
    
    return output

if __name__ == "__main__":
    main()