#!/usr/bin/env python3
"""
CVG Test Generator - GitHub Action Core
Generate unit tests, integration tests, and E2E tests automatically
"""
import argparse
import json
import os
import sys
from pathlib import Path
from datetime import datetime

def analyze_code(path: str, language: str):
    """Analyze source code to identify testable functions/classes"""
    testable_items = []
    path = Path(path)
    
    if language == "auto":
        # Auto-detect from file extensions
        py_files = list(path.rglob("*.py"))
        rs_files = list(path.rglob("*.rs"))
        ts_files = list(path.rglob("*.ts"))
        
        if py_files:
            language = "python"
            files = py_files
        elif rs_files:
            language = "rust"
            files = rs_files
        elif ts_files:
            language = "typescript"
            files = ts_files
        else:
            return testable_items
    else:
        extensions = {"python": "*.py", "rust": "*.rs", "typescript": "*.ts", "go": "*.go"}
        files = list(path.rglob(extensions.get(language, "*.py")))
    
    for file in files[:20]:  # Limit to 20 files
        try:
            content = file.read_text()
            # Simple extraction of function/class definitions
            if language == "python":
                for line in content.split('\n'):
                    if line.strip().startswith('def ') and not line.strip().startswith('def _'):
                        func_name = line.split('def ')[1].split('(')[0]
                        testable_items.append({"file": str(file), "type": "function", "name": func_name})
            elif language == "rust":
                for line in content.split('\n'):
                    if 'fn ' in line and not 'fn _' in line:
                        func_name = line.split('fn ')[1].split('(')[0].strip()
                        testable_items.append({"file": str(file), "type": "function", "name": func_name})
        except Exception as e:
            print(f"Error analyzing {file}: {e}")
    
    return testable_items, language

def generate_tests(items, language, test_type):
    """Generate test code based on analysis"""
    tests = []
    
    if language == "python":
        for item in items:
            test_code = f'''
def test_{item["name"]}():
    """Test for {item['name']} - auto-generated by CVG Test Generator"""
    # TODO: Add assertions for {item['name']}
    # File: {item['file']}
    pass
'''
            tests.append({"file": item["file"], "test": test_code})
    
    return tests

def main():
    parser = argparse.ArgumentParser(description='CVG Test Generator')
    parser.add_argument('-target-path', nargs='?', default='.')
    parser.add_argument('-language', nargs='?', default='auto')
    parser.add_argument('-test-type', nargs='?', default='unit')
    parser.add_argument('-coverage', nargs='?', default='80')
    
    args, _ = parser.parse_known_args()
    
    print(f"[{datetime.now().isoformat()}] Analyzing {args.target_path}...")
    
    items, lang = analyze_code(args.target_path, args.language)
    print(f"Found {len(items)} testable items in {lang}")
    
    tests = generate_tests(items, lang, args.test_type)
    
    output = {
        "analysis": {
            "path": args.target_path,
            "language": lang,
            "test_type": args.test_type,
            "coverage_target": args.coverage,
            "items_found": len(items)
        },
        "tests": tests,
        "generated_at": datetime.now().isoformat()
    }
    
    print(json.dumps(output, indent=2))
    
    # Save results
    output_path = Path(args.target_path) / ".cvg-tests" / f"{args.test_type}_output.json"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(json.dumps(output, indent=2))
    print(f"\nResults saved to {output_path}")
    
    return output

if __name__ == "__main__":
    main()